INSERT INTO `categories` (`id`, `enName`, `etName`, `ruName`)
VALUES (1, 'Automotive glass', 'Autoklaasid', 'Автомобильное стекло'),
       (2, 'Autochemistry and autocosmetics', 'Autokeemia ja autokosmeetika', 'Автохимия и автокосметика'),
       (3, 'Accessories and supplies', 'Tarvikud ja tarvikud', 'Аксессуары и принадлежности'),
       (4, 'Shock absorbers and springs', 'Amortisaatorid ja vedrud', 'Амортизаторы и пружины'),
       (5, 'Gas springs', 'Gaasivedrud', 'Газовые пружины'),
       (6, 'Engine', 'Mootor', 'Двигатель'),
       (7, 'Tuning parts', 'Osade häälestamine', 'Запчасти для тюнинга'),
       (8, 'Sound signals', 'Helisignaalid', 'Звуковые сигналы'),
       (9, 'Mirrors', 'Peeglid', 'Зеркала'),
       (10, 'Instruments', 'Instrumendid', 'Инструменты'),
       (11, 'Wheels', 'Rattad', 'Колеса'),
       (12, 'Transmission', 'Edasikandumine', 'Коробка передач'),
       (13, 'Fasteners', 'Kinnitusvahendid', 'Крепежи'),
       (14, 'Body', 'Keha', 'Кузов'),
       (15, 'Oils', 'Õlid', 'Масла'),
       (16, 'Heating', 'Küte', 'Обогрев'),
       (17, 'Workshop equipment', 'Töökoja varustus', 'Оборудование для мастерских'),
       (18, 'Optics', 'Optika', 'Оптика'),
       (19, 'Cooling', 'Jahutus', 'Охлаждение'),
       (20, 'Switches', 'Lülitid', 'Переключатели'),
       (21, 'Suspension and control', 'Vedrustus ja juhtimine', 'Подвеска и управление'),
       (22, 'Bearings universal', 'Universaalsed laagrid', 'Подшипники универсальные'),
       (23, 'Bearings are universal', 'Laagrid on universaalsed', 'Подшипники универсальные'),
       (24, 'Drive unit', 'Ajam', 'Привод'),
       (25, 'Other', 'Muu', 'Прочее'),
       (26, 'Belts and rollers', 'Rihmad ja rullid', 'Ремни и ролики'),
       (27, 'Salon', 'Salong', 'Салон'),
       (28, 'Intake system', 'Sisselaskesüsteem', 'Система впуска'),
       (29, 'Exhaust system', 'Väljalaskesüsteem', 'Система выпуска'),
       (30, 'Wipers', 'Klaasipuhastid', 'Стеклоочистители'),
       (31, 'Power windows', 'Elektrilised aknad', 'Стеклоподъемники'),
       (32, 'Clutch', 'Sidur', 'Сцепление'),
       (33, 'Fuel system', 'Kütusesüsteem', 'Топливная система'),
       (34, 'Brakes', 'Pidurid', 'Тормоза'),
       (35, 'Filters', 'Filtrid', 'Фильтры'),
       (36, 'Chemistry', 'Keemia', 'Химия'),
       (37, 'Electrician', 'Elektrik', 'Электрика'),
       (38, 'Security elements', 'Turvaelemendid', 'Элементы охраны'),
       (39, 'Suspension elements and control systems', 'Vedrustuselemendid ja juhtimissüsteemid',
        'Элементы подвески и системы управления');
