<?php

return [
    "sk" => env("STRIPE_SK"),
    "pk" => env("STRIPE_PK"),
    "webhook_secret" => env("STRIPE_WEBHOOK_SECRET"),

    "available_countries" => [
        "AT",
        "BE",
        "BG",
        "HR",
        "CY",
        "CZ",
        "DK",
        "EE",
        "FI",
        "FR",
        "DE",
        "GR",
        "HU",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MT",
        "NL",
        "PL",
        "PT",
        "RO",
        "SK",
        "SI",
        "ES",
        "SE",
        "GB",
    ],
];
